name: DartWebServer
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.instantobjects.com
# author: Chris <chrisr@instantobjects.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  exif:
  http_server:
  path:


dev_dependencies:
  test: ^1.0.0
  http: