name: DartWebServer
description: Old AllOurPhotosServer.
# version: 1.0.0
# homepage: https://www.instantobjects.com
# author: Chris <chrisr@instantobjects.com>

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  exif:
  http_server:
  path:


dev_dependencies:
  test: ^1.15.4
  http: